image: docker:19.03.5

services:
    - docker:19.03.1-dind

before_script:
    - docker info

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - echo "building"
        - docker run hello-world
        - docker build -t interaze/service-driver ./ServiceDriver
        - docker build -t interaze/dynamic-front ./FrontEnd
        - docker build -t interaze/statuc-front ./FrontEnd/nginx
        - echo "$DockerUser" | docker login -u "$DockerPass" --password-stdin

testFrontStatic:
    stage: test
    script:
        - echo "Test"

testFrontPHP:
    stage: test
    script:
        - echo "Test"

deploy:
    stage: deploy
    only:
        - master
    script:
        - echo "deployed system"
