image: docker:19.03.5

services:
    - docker:19.03.1-dind

before_script:
    - docker info

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - echo "Building"
        - docker build -t hello-world .
        - docker run hello-world
    artifacts:
        paths:
            - build/

testFrontStatic:
    stage: test
    script:
        - echo "Test"
        - test -f "build/info.txt"

testFrontPHP:
    stage: test
    script:
        - echo "Test"
        - test -f "build/info.txt"

deploy:
    stage: deploy
    only:
        - master
    script:
        - echo "deployed system"
