version: '3'
services:
    
  service_balance:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./ServiceDriver
    volumes:
      - ./ServiceDriver/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '3050:80'
    links:
      - static_front

  static_front:
    build:
      dockerfile: Dockerfile.dev
      context: ./FrontEnd/nginx
    volumes:
      - ./FrontEnd/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./FrontEnd:/code
    links:
      - dynamic_front

  dynamic_front:
    build:
      dockerfile: Dockerfile.dev
      context: ./FrontEnd
    volumes:
      - ./FrontEnd:/code
