USE MU3DPC;

ALTER TABLE PROJECTS DROP FOREIGN KEY FK_PROJECTS;
ALTER TABLE EVENTS DROP FOREIGN KEY FK_EVENTS;
ALTER TABLE MEMBERS DROP FOREIGN KEY FK_MEMBERS;

DROP TABLE SUBGROUPS;
DROP TABLE PROJECTS;
DROP TABLE EVENTS;
DROP TABLE MEMBERS;
